### ISSUE TITLE
Data cannot be uploaded due to the size issue

### ISSUE THREAD

**Issue by jessicajysong** [uchicagods/examples#1]

**Comment by jesteria** [comment]
Could you clarify beyond "data" and the "size issue"?

Just a guess -- were you unable to upload a Jupyter Notebook because the file is larger than 100 MB?

If that's the case, I'm not sure, off-hand, the best way forward. Github does not allow such large files.

1. You could simply [clear all notebook outputs](https://stackoverflow.com/a/51531103). This would likely make the file **much** smaller. While not ideal, it should be reasonably safe -- it shouldn't be too hard for people to re-run the notebook locally. However, they *could* run into problems. And, we won't be able to preview the notebook's outputs in Github.

1. You could use [Git Large File Storage](https://git-lfs.github.com), at least for files up to 2 GB in size. [Github has documentation for this](https://help.github.com/en/articles/versioning-large-files).
